### ISSUE TITLE
Reviva declares itself as the B9PartSwitch KSPAssembly

### ISSUE THREAD

**Issue by JonnyOThan** [harveyt/reviva#12]
https://github.com/harveyt/reviva/blob/be116cea69304b2882d98b174e7d57086b60adb1/plugin/AssemblyInfo.cs.in#L21

This seems like a copy/paste mistake.  Unless this was supposed to be KSPAssembly*DEPENDENCY*

**Comment by harveyt** [comment]
I'm not sure what KSPAssembly does, but certainly seems like it's copy-paste error. Other mods don't do this, I checked several.

**Comment by JonnyOThan** [comment]
KSPAssembly declares what mod this is and what version it is (this should, but doesn't have to, correspond to the file version).  KSPAssemblyDependency lets you declare dependcies on other mods' KSPAssembly version info - if the dependency isn't met, your mod will not be loaded.
